version: '3.7'
services:
  app: 
    image: node:17
    volumes:
      - .:/app
    ports:
      - 8080:8080
    command: npm run dev --prefix /app
    # command: bash -c "while true; do sleep 360; done"
    